[package]
name = "marshr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2.33"
indexmap = "2.5.0"
libc = "0.2.155"
paste = "1.0.15"
